name: Discover
description: Scopri e ispeziona i dispositivi collegati alla tua rete WiFi

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  noise_meter: ^1.0.1
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.7
  flutter_circular_chart: ^0.1.0
  google_nav_bar: ^2.0.0
  simple_animations: ^2.1.1
  spring_button: ^1.0.13
  flip_card: ^0.4.4
  theme_provider: ^0.3.2
  avatar_glow: ^1.1.0
  intl: ^0.16.1
  flare_flutter: ^2.0.3
  flutter_slidable: ^0.5.4
  fl_chart: ^0.9.4
  flutter_swiper: ^1.1.6
  flutter_custom_clippers: ^1.1.1
  permission_handler: ^5.0.0+hotfix.6
  listview_utils: ^0.1.6+1

dev_dependencies:
  hive_generator: ^0.7.0+2
  build_runner: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/flares/recording.flr
    - assets/images/tracks_light.png
    - assets/images/tracks_dark.png
    - assets/images/saved_dark.png
    - assets/images/saved_light.png
    - assets/images/settings_dark.png
    - assets/images/settings_light.png
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
