name: Discover
description: Scopri e ispeziona i dispositivi collegati alla tua rete WiFi

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  noise_meter: ^1.0.1
  flutter_circular_chart: ^0.1.0
  google_nav_bar: ^2.0.0
  simple_animations: ^1.3.8
  spring_button: ^1.0.13
  flip_card: ^0.4.4
  theme_provider: ^0.3.2
  avatar_glow: ^1.1.0
  intl: ^0.16.1
  flare_flutter: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/flares/recording.flr
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
